apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "rancher-token-revoker.labels" . | nindent 4 }}
  name: revoker-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: revoker-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-token-revoker.fullname" . }}
    namespace: {{ .Release.Namespace }}
