# permissions for end users to view gitreposcans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitreposcan-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rancher-token-revoker
    app.kubernetes.io/part-of: rancher-token-revoker
    app.kubernetes.io/managed-by: kustomize
  name: gitreposcan-viewer-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - gitreposcans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - gitreposcans/status
  verbs:
  - get
