# permissions for end users to edit scanexceptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scanexception-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rancher-token-revoker
    app.kubernetes.io/part-of: rancher-token-revoker
    app.kubernetes.io/managed-by: kustomize
  name: scanexception-editor-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - scanexceptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - scanexceptions/status
  verbs:
  - get
