//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOrgScan) DeepCopyInto(out *GitOrgScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOrgScan.
func (in *GitOrgScan) DeepCopy() *GitOrgScan {
	if in == nil {
		return nil
	}
	out := new(GitOrgScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOrgScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOrgScanList) DeepCopyInto(out *GitOrgScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOrgScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOrgScanList.
func (in *GitOrgScanList) DeepCopy() *GitOrgScanList {
	if in == nil {
		return nil
	}
	out := new(GitOrgScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOrgScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOrgScanSpec) DeepCopyInto(out *GitOrgScanSpec) {
	*out = *in
	in.OrgScanConfig.DeepCopyInto(&out.OrgScanConfig)
	out.RepoScanConfig = in.RepoScanConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOrgScanSpec.
func (in *GitOrgScanSpec) DeepCopy() *GitOrgScanSpec {
	if in == nil {
		return nil
	}
	out := new(GitOrgScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOrgScanStatus) DeepCopyInto(out *GitOrgScanStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOrgScanStatus.
func (in *GitOrgScanStatus) DeepCopy() *GitOrgScanStatus {
	if in == nil {
		return nil
	}
	out := new(GitOrgScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepoScan) DeepCopyInto(out *GitRepoScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepoScan.
func (in *GitRepoScan) DeepCopy() *GitRepoScan {
	if in == nil {
		return nil
	}
	out := new(GitRepoScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitRepoScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepoScanList) DeepCopyInto(out *GitRepoScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitRepoScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepoScanList.
func (in *GitRepoScanList) DeepCopy() *GitRepoScanList {
	if in == nil {
		return nil
	}
	out := new(GitRepoScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitRepoScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepoScanSpec) DeepCopyInto(out *GitRepoScanSpec) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepoScanSpec.
func (in *GitRepoScanSpec) DeepCopy() *GitRepoScanSpec {
	if in == nil {
		return nil
	}
	out := new(GitRepoScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepoScanStatus) DeepCopyInto(out *GitRepoScanStatus) {
	*out = *in
	if in.ScanError != nil {
		in, out := &in.ScanError, &out.ScanError
		*out = new(RepoScanError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepoScanStatus.
func (in *GitRepoScanStatus) DeepCopy() *GitRepoScanStatus {
	if in == nil {
		return nil
	}
	out := new(GitRepoScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrgScanConfig) DeepCopyInto(out *GithubOrgScanConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrgScanConfig.
func (in *GithubOrgScanConfig) DeepCopy() *GithubOrgScanConfig {
	if in == nil {
		return nil
	}
	out := new(GithubOrgScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgScanConfig) DeepCopyInto(out *OrgScanConfig) {
	*out = *in
	if in.GithubOrgScanConfig != nil {
		in, out := &in.GithubOrgScanConfig, &out.GithubOrgScanConfig
		*out = new(GithubOrgScanConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgScanConfig.
func (in *OrgScanConfig) DeepCopy() *OrgScanConfig {
	if in == nil {
		return nil
	}
	out := new(OrgScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoScanConfig) DeepCopyInto(out *RepoScanConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoScanConfig.
func (in *RepoScanConfig) DeepCopy() *RepoScanConfig {
	if in == nil {
		return nil
	}
	out := new(RepoScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoScanError) DeepCopyInto(out *RepoScanError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoScanError.
func (in *RepoScanError) DeepCopy() *RepoScanError {
	if in == nil {
		return nil
	}
	out := new(RepoScanError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanException) DeepCopyInto(out *ScanException) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanException.
func (in *ScanException) DeepCopy() *ScanException {
	if in == nil {
		return nil
	}
	out := new(ScanException)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanException) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanExceptionList) DeepCopyInto(out *ScanExceptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScanException, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanExceptionList.
func (in *ScanExceptionList) DeepCopy() *ScanExceptionList {
	if in == nil {
		return nil
	}
	out := new(ScanExceptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScanExceptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanExceptionSpec) DeepCopyInto(out *ScanExceptionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanExceptionSpec.
func (in *ScanExceptionSpec) DeepCopy() *ScanExceptionSpec {
	if in == nil {
		return nil
	}
	out := new(ScanExceptionSpec)
	in.DeepCopyInto(out)
	return out
}
